export enum ACTIVITY_TYPE {
  POST_LIKE = "POST_LIKE",
  FOLLOW_USER = "FOLLOW_USER",
  CREATE_COMMENT = "CREATE_COMMENT",
  COMMENT_LIKE = "COMMENT_LIKE",
  CREATE_REPLY = "CREATE_REPLY",
  REPLY_LIKE = "REPLY_LIKE",
}
