/*** @type {import("prettier").Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/src/env(.*)$",
    "^@/src/types/(.*)$",
    "^@/src/config/(.*)$",
    "^@/src/lib/(.*)$",
    "^@/src/hooks/(.*)$",
    "^@/src/components/ui/(.*)$",
    "^@/src/components/(.*)$",
    "^@/src/styles/(.*)$",
    "^@/src/app/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["prettier-plugin-tailwindcss"],
};
